#!/bin/zsh

# smctl is a wrapper over the normal Service Manager CLI used temporarily for creating
# Cloud Foundry visibilities manually when the 'register-broker' command is issued

service-manager-cli $1 $2 $3 $4 $5 $6 $7 $8 $9 $10

if [ $1 = "register-broker" ]; then
  enableCFVisibility
fi
